version: '3.8'

services:
  # Zookeeper service (required by Kafka)
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  # Kafka service
  kafka:
    image: wurstmeister/kafka:latest
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE_LISTENER: INSIDE
      KAFKA_LISTENER_NAME_OUTSIDE_LISTENER: OUTSIDE
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENER_INTERNAL_HOSTNAME: kafka
      KAFKA_LISTENER_OUTSIDE_HOSTNAME: localhost
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"   # For external access
      - "9093:9093"   # Internal port for communication between Kafka and Zookeeper
    depends_on:
      - zookeeper
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge
